# Generated by Django 5.2 on 2025-05-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedTranasaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=50)),
                ('TXN_DATE', models.DateField(blank=True, max_length=50, null=True)),
                ('IRCTC_ORDER_NO', models.CharField(blank=True, max_length=50, null=True)),
                ('BANK_BOOKING_REF_NO', models.CharField(blank=True, max_length=50, null=True)),
                ('BOOKING_AMOUNT', models.IntegerField(blank=True, max_length=50, null=True)),
                ('CREDITED_ON', models.DateField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
