# Generated by Django 5.2 on 2025-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandas_django_use', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedtranasaction',
            name='BOOKING_AMOUNT',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
